server:
  port: ${SERVER_PORT:18102}
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    use-global-registry: true

logging:
  level:
    root: INFO
