#!/usr/bin/env bash
# Phase 2 Unit 6 Formal Benchmark — Native macOS ARM64 full matrix driver.
#
# - Full 18-run matrix: P-E x {R3,R6,R8} x 3 reps + VT-Limited x {R3,R6,R8} x 3 reps.
# - Results land under docs/test-results/phase2/unit6-native/ (separate from
#   the Docker harness's docs/test-results/phase2/unit6/ — see
#   docs/decisions/phase2-formal-native-macos-environment.md).
# - The "P-E R3 Native Stability Canary" is NOT part of this 18-run matrix.
# - Run this script only after the Native Stability Canary has passed AND the
#   user has explicitly approved running the full matrix.
#
# Run order (2026-08-19, user-directed, see ADR §15 "Formal run ordering"):
# P-E and VT-Limited are INTERLEAVED within each rep (not blocked as 9+9) so
# that time-of-day/thermal/host-state drift over this long native macOS run
# doesn't correlate with one config more than the other. Rate order within a
# rep is always R3->R6->R8; which config goes first alternates rep-to-rep
# (rep1: P-E first, rep2: VT-Limited first, rep3: P-E first). run_number
# (the 7th field, used in each run's output dir name) is the rep index
# (1/2/3) regardless of interleave position — unrelated to execution order.
set -uo pipefail  # NOT -e: the validity gate below needs to run and report
                   # even if a run's own exit code is non-zero.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

# config_label thread_mode load rate warmup_s measurement_s run_number
RUNS=(
  # --- rep 1 (P-E first) ---
  "pe PLATFORM r3 3 120 300 1"
  "vtl VIRTUAL_LIMITED r3 3 120 300 1"
  "pe PLATFORM r6 6 120 300 1"
  "vtl VIRTUAL_LIMITED r6 6 120 300 1"
  "pe PLATFORM r8 8 120 300 1"
  "vtl VIRTUAL_LIMITED r8 8 120 300 1"
  # --- rep 2 (VT-Limited first) ---
  "vtl VIRTUAL_LIMITED r3 3 120 300 2"
  "pe PLATFORM r3 3 120 300 2"
  "vtl VIRTUAL_LIMITED r6 6 120 300 2"
  "pe PLATFORM r6 6 120 300 2"
  "vtl VIRTUAL_LIMITED r8 8 120 300 2"
  "pe PLATFORM r8 8 120 300 2"
  # --- rep 3 (P-E first) ---
  "pe PLATFORM r3 3 120 300 3"
  "vtl VIRTUAL_LIMITED r3 3 120 300 3"
  "pe PLATFORM r6 6 120 300 3"
  "vtl VIRTUAL_LIMITED r6 6 120 300 3"
  "pe PLATFORM r8 8 120 300 3"
  "vtl VIRTUAL_LIMITED r8 8 120 300 3"
)

# ---- Per-run validity gate (2026-08-19 revision — see ADR §14) ----
# Reads only artifacts the per-run script already produces (result.json,
# environment.json, stall_check.json, counter-plateau-check.json) — no
# changes to measurement lifecycle/collector/k6. counter-plateau-check.json
# is the authoritative environment-stability signal: the per-run script
# query_range's gateway_request_received_total/mockllm_completed_requests_total
# against its own live Prometheus BEFORE tearing it down (see that script),
# so this driver only reads the saved result rather than querying Prometheus
# itself. Missing/failed file, or either counter plateauing >20s, is a hard
# INVALID. The older log-gap heuristic is kept as an advisory cross-check
# only (see below) — it is no longer sufficient by itself to fail a run.
check_run_validity() {
  local out_dir="$1"
  python3 - "${out_dir}" <<'PYEOF'
import json, os, sys

out_dir = sys.argv[1]

def load(name):
    with open(os.path.join(out_dir, name)) as f:
        return json.load(f)

fail_reasons = []

try:
    result = load("result.json")
except Exception as e:
    print(f"INVALID: could not read result.json: {e}")
    sys.exit(1)

dropped = result.get("dropped_iterations")
if dropped not in (0, None):
    fail_reasons.append(f"dropped_iterations={dropped}")

cohort = result.get("client_cohort", {})
if cohort.get("invariant_ok") is not True:
    fail_reasons.append(f"client_cohort.invariant_ok={cohort.get('invariant_ok')}")
# invariant_ok only means accounting balances (started = completed + rejected
# + failed_mid_stream + failed_no_event) — it does NOT mean zero failures.
# rejected is deliberately NOT gated here: at R8 (over-capacity), rejection
# is the expected overload-experiment outcome, not an environment problem.
failed_mid_stream = cohort.get("failed_mid_stream")
if failed_mid_stream not in (0, None):
    fail_reasons.append(f"client_cohort.failed_mid_stream={failed_mid_stream}")
failed_no_event = cohort.get("failed_no_event")
if failed_no_event not in (0, None):
    fail_reasons.append(f"client_cohort.failed_no_event={failed_no_event}")

try:
    env = load("environment.json")
    postflight_fail = env.get("postflight_fail", "")
    if postflight_fail:
        fail_reasons.append(f"postflight_fail='{postflight_fail}'")
except Exception as e:
    fail_reasons.append(f"could not read environment.json: {e}")

# Counter-plateau evidence (Formal integrity check, see ADR §14/§1-1 update
# 2026-08-19) — the authoritative environment-stability signal, generated by
# the per-run script BEFORE its Prometheus/TSDB teardown. dropped file,
# failed query, or either counter plateauing >20s (same threshold as the
# log-gap heuristic below, for a consistent Formal-integrity bar) is a hard
# INVALID — this, not the log gap, is now the primary stall detector.
try:
    plateau = load("counter-plateau-check.json")
    if not plateau.get("query_ok", False):
        fail_reasons.append(
            f"counter-plateau-check query_ok=False: {plateau.get('query_error', 'unknown')}"
        )
    elif plateau.get("plateau_over_20s"):
        fail_reasons.append(
            f"counter plateau > 20s: gateway={plateau.get('gateway_max_plateau_seconds')}s "
            f"mock={plateau.get('mock_max_plateau_seconds')}s"
        )
except Exception as e:
    fail_reasons.append(f"could not read counter-plateau-check.json: {e}")

# Log gap stays advisory-only (downgraded from a earlier draft where it was
# a hard gate) — the counter-plateau check above is the authoritative,
# purpose-built signal now; log gap alone no longer determines stall/no-stall.
try:
    stall = load("stall_check.json")
    gw_gaps = stall.get("gateway_log_gaps_over_20s", [])
    ml_gaps = stall.get("mock_llm_log_gaps_over_20s", [])
    if gw_gaps or ml_gaps:
        print(f"advisory: log gaps present (gateway={len(gw_gaps)} mock={len(ml_gaps)}) — "
              f"see stall_check.json; not blocking by itself, cross-checked against "
              f"counter-plateau-check.json above")
except Exception as e:
    print(f"advisory: could not read stall_check.json: {e}")

target = result.get("arrival_rate_target")
completion = result.get("measurement_window_completion_rate")
if target and completion is not None:
    print(f"advisory: measurement_window_completion_rate={completion} vs target={target} "
          f"(informational only, not a pass/fail threshold)")

if fail_reasons:
    print("INVALID: " + "; ".join(fail_reasons))
    sys.exit(1)
print("VALID")
sys.exit(0)
PYEOF
}

TOTAL=${#RUNS[@]}
I=0
for spec in "${RUNS[@]}"; do
  I=$((I+1))
  echo "##### NATIVE MATRIX [$I/$TOTAL]: ${spec} #####"
  # shellcheck disable=SC2086
  ./scripts/run-phase2-native-formal-benchmark.sh ${spec} 100
  RC=$?

  # shellcheck disable=SC2086
  read -r CONFIG_LABEL THREAD_MODE LOAD_LABEL RATE WARMUP_SEC MEASUREMENT_SEC RUN_NUMBER <<< "${spec}"
  OUT_DIR="${ROOT}/docs/test-results/phase2/unit6-native/${CONFIG_LABEL}-${LOAD_LABEL}-run${RUN_NUMBER}"

  if [ ${RC} -ne 0 ]; then
    echo "##### NATIVE MATRIX [$I/$TOTAL] FAILED (script exit ${RC}): ${spec} #####" >&2
    [ -d "${OUT_DIR}" ] && mv "${OUT_DIR}" "${OUT_DIR}-INVALID-script-exit-${RC}"
    echo "##### NATIVE MATRIX HALTED at [$I/$TOTAL] — not proceeding to remaining runs. Investigate before resuming. #####" >&2
    exit 1
  fi

  VALIDITY_OUTPUT=$(check_run_validity "${OUT_DIR}")
  VALIDITY_RC=$?
  echo "${VALIDITY_OUTPUT}"
  if [ ${VALIDITY_RC} -ne 0 ]; then
    echo "##### NATIVE MATRIX [$I/$TOTAL] INVALID: ${spec} #####" >&2
    mv "${OUT_DIR}" "${OUT_DIR}-INVALID-review-needed"
    echo "##### NATIVE MATRIX HALTED at [$I/$TOTAL] — not proceeding to remaining runs. Investigate before resuming (see ${OUT_DIR}-INVALID-review-needed). #####" >&2
    exit 1
  fi

  echo "##### NATIVE MATRIX [$I/$TOTAL] OK: ${spec} #####"
done
echo "##### NATIVE MATRIX ALL DONE — ${TOTAL}/${TOTAL} valid #####"
