#!/usr/bin/env bash
# Runs one Unit 5 Executor Matrix Screening data point: fresh gateway+mock-llm,
# one k6 scenario-01 (closed-model concurrent connections) run at a given
# concurrency, drain, collect result row. See docs/test-results/phase1/
# unit5-executor-matrix-screening.md for the matrix this feeds.
#
# Usage: ./scripts/run-screening.sh <label> <core> <max> <queueCapacity> <rejection> <concurrency>
#   queueCapacity <= 0 means SynchronousQueue (see ChatExecutorConfig).
set -euo pipefail

LABEL="$1"; CORE="$2"; MAX="$3"; QUEUE_CAP="$4"; REJECTION="$5"; CONCURRENCY="$6"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESULTS_DIR="${ROOT}/docs/test-results/phase1/unit5-raw"
mkdir -p "${RESULTS_DIR}"
RUN_ID="${LABEL}-vus${CONCURRENCY}"
SUMMARY_JSON="${RESULTS_DIR}/${RUN_ID}-k6-summary.json"
K6_LOG="${RESULTS_DIR}/${RUN_ID}-k6.log"

cd "${ROOT}"

# Docker Desktop's Linux VM clock has been observed to drift several minutes
# after a host sleep/wake during this project's long sessions (silently
# invalidates every timeout/latency measurement in a run — the container's
# own AsyncContext timeout fires correctly by ITS clock, just far from real
# wall time). Abort rather than collect garbage data.
HOST_EPOCH=$(date +%s)
CONTAINER_EPOCH=$(docker run --rm alpine date +%s)
DRIFT=$(( HOST_EPOCH > CONTAINER_EPOCH ? HOST_EPOCH - CONTAINER_EPOCH : CONTAINER_EPOCH - HOST_EPOCH ))
if [ "${DRIFT}" -gt 5 ]; then
  echo "[${RUN_ID}] FATAL: host/container clock drift ${DRIFT}s — restart Docker Desktop before running Screening" >&2
  exit 1
fi

cat > docker-compose.override.yml <<EOF
# Auto-generated by scripts/run-screening.sh for run ${RUN_ID} — do not edit by hand.
services:
  gateway:
    environment:
      MOCK_LLM_BASE_URL: http://mock-llm:8000
      CHAT_CORE_POOL_SIZE: "${CORE}"
      CHAT_MAX_POOL_SIZE: "${MAX}"
      CHAT_QUEUE_CAPACITY: "${QUEUE_CAP}"
      CHAT_REJECTION_POLICY: ${REJECTION}
      CHAT_CONNECT_TIMEOUT_MS: "3000"
      CHAT_READ_TIMEOUT_MS: "30000"
      CHAT_TOTAL_TIMEOUT_MS: "60000"
EOF

echo "[${RUN_ID}] recreating mock-llm + gateway with fresh state..."
docker compose up -d --force-recreate mock-llm gateway >/dev/null

# Wait for both to report healthy.
for i in $(seq 1 30); do
  GW_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' llm-concurrency-lab-gateway-1 2>/dev/null || echo "starting")
  ML_HEALTH=$(docker inspect --format='{{.State.Health.Status}}' llm-concurrency-lab-mock-llm-1 2>/dev/null || echo "starting")
  if [ "${GW_HEALTH}" = "healthy" ] && [ "${ML_HEALTH}" = "healthy" ]; then
    break
  fi
  sleep 1
done
if [ "${GW_HEALTH}" != "healthy" ] || [ "${ML_HEALTH}" != "healthy" ]; then
  echo "[${RUN_ID}] FATAL: containers did not become healthy (gateway=${GW_HEALTH} mock-llm=${ML_HEALTH})" >&2
  exit 1
fi

NET=$(docker network ls --format '{{.Name}}' | grep llm-lab)
START_TS=$(date +%s)
echo "[${RUN_ID}] start_ts=${START_TS} concurrency=${CONCURRENCY}"

docker run --rm --network "${NET}" \
  -v "${ROOT}/load-test-k6/scenarios:/scripts:ro" \
  -v "${RESULTS_DIR}:/results" \
  -e GATEWAY_URL=http://gateway:8080/chat/stream \
  -e VUS="${CONCURRENCY}" \
  -e K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write \
  -e "K6_PROMETHEUS_RW_TREND_STATS=p(50),p(95),p(99),min,max" \
  --entrypoint k6 k6-sse:dev run \
  -o experimental-prometheus-rw \
  --summary-trend-stats "p(50),p(95),p(99),min,max" \
  --summary-export "/results/$(basename "${SUMMARY_JSON}")" \
  /scripts/01-concurrent-connections.js > "${K6_LOG}" 2>&1 || echo "[${RUN_ID}] k6 exited non-zero (may be expected if scenario itself reports failures)"

echo "[${RUN_ID}] k6 run finished, waiting for gateway drain..."
for i in $(seq 1 90); do
  ACTIVE=$(curl -s -m 3 http://localhost:8080/metrics | awk '/^gateway_async_active_requests /{print $2}')
  if [ "${ACTIVE}" = "0.0" ] || [ "${ACTIVE}" = "0" ]; then
    break
  fi
  sleep 1
done
echo "[${RUN_ID}] drained, waiting for Prometheus's next scrape (scrape_interval=5s) to pick up the final state..."
sleep 8
END_TS=$(date +%s)
echo "[${RUN_ID}] end_ts=${END_TS} (async_active=${ACTIVE:-unknown})"

python3 "${ROOT}/scripts/collect_screening_result.py" "${LABEL}" "${CONCURRENCY}" "${START_TS}" "${END_TS}" "${SUMMARY_JSON}" http://localhost:9091 \
  | tee -a "${RESULTS_DIR}/results.ndjson"
